<?php
require __DIR__.'/includes/app.php'; require_login(); $errors=[];
if ($_SERVER['REQUEST_METHOD']==='POST') {
 $name=trim((string)($_POST['name']??'')); $target=amount($_POST['target']??null); $installment=amount($_POST['installment']??null); $frequency=(string)($_POST['frequency']??''); $start=(string)($_POST['start']??'');
 if(!valid_form('goal')) { notice('Formulir ini sudah diproses. Jadwal tidak dibuat dua kali.','info'); go('jadwal.php'); }
 if($name==='' || preg_match_all('/./us', $name)>100) $errors[]='Nama tujuan wajib diisi, maksimal 100 karakter.';
 if(!$target) $errors[]='Target harus berupa angka bulat antara Rp1 dan Rp1.000.000.000.';
 if(!$installment || ($target && $installment>$target)) $errors[]='Nominal rutin harus positif dan tidak melebihi target.';
 if(!in_array($frequency,['Harian','Mingguan'],true)) $errors[]='Pilih frekuensi harian atau mingguan.';
 if(!date_ok($start) || $start<date('Y-m-d') || $start>date('Y-m-d',strtotime('+5 years'))) $errors[]='Tanggal mulai harus hari ini hingga 5 tahun ke depan.';
 if(count($_SESSION['goals'])>=MAX_GOALS) $errors[]='Maksimal '.MAX_GOALS.' jadwal dalam satu sesi demo.';
 if(!$errors) { $id=bin2hex(random_bytes(8)); $_SESSION['goals'][$id]=['id'=>$id,'name'=>$name,'target'=>$target,'installment'=>$installment,'frequency'=>$frequency,'start'=>$start]; unset($_SESSION['forms']['goal']); notice('Jadwal berhasil dibuat. Sekarang Anda bisa mulai deposit.'); go('jadwal.php'); }
}
page_start('Jadwal tabungan','jadwal','Tentukan apa yang ingin dicapai dan seberapa sering Anda menabung.'); errors($errors);
?><div class="two-col"><section class="panel"><div class="section-title"><h2>Buat jadwal baru</h2><span class="icon-box soft"><?=icon('calendar')?></span></div><form method="post" action="jadwal.php"><?=csrf()?><?=form_id('goal')?><label for="name">Nama tujuan</label><input id="name" name="name" maxlength="100" placeholder="Contoh: Beli sepatu baru" value="<?=old('name')?>" required><div class="form-grid"><div><label for="target">Target tabungan (Rp)</label><input id="target" name="target" type="number" min="1" max="1000000000" step="1" placeholder="500000" value="<?=old('target')?>" required></div><div><label for="installment">Nominal rutin (Rp)</label><input id="installment" name="installment" type="number" min="1" max="1000000000" step="1" placeholder="5000" value="<?=old('installment')?>" required></div></div><div class="form-grid"><div><label for="frequency">Frekuensi</label><select id="frequency" name="frequency"><option value="Harian" <?=($_POST['frequency']??'')==='Harian'?'selected':''?>>Setiap hari</option><option value="Mingguan" <?=($_POST['frequency']??'')==='Mingguan'?'selected':''?>>Setiap minggu</option></select></div><div><label for="start">Tanggal mulai</label><input id="start" name="start" type="date" min="<?=date('Y-m-d')?>" max="<?=date('Y-m-d',strtotime('+5 years'))?>" value="<?=old('start',date('Y-m-d'))?>" required></div></div><div class="info-note">Jadwal menjadi panduan menabung. Deposit dilakukan sendiri, tanpa penarikan otomatis.</div><button class="btn primary full" type="submit">Simpan jadwal</button></form></section><section><div class="section-title"><h2>Tujuanmu</h2><span class="pill"><?=count($_SESSION['goals'])?> jadwal</span></div><?php if(!$_SESSION['goals']): ?><div class="panel empty"><span class="icon-box"><?=icon('target')?></span><h3>Setiap tujuan punya awal</h3><p>Isi formulir di samping untuk membuat jadwal pertama.</p></div><?php else: foreach(array_reverse($_SESSION['goals']) as $g): $p=progress($g); ?><article class="panel goal-card"><div class="section-title"><h3><?=e($g['name'])?></h3><span class="pill"><?=e($g['frequency'])?></span></div><div class="goal-amount"><strong><?=rp(saved($g['id']))?></strong><span> / <?=rp($g['target'])?></span></div><progress value="<?=$p?>" max="100" aria-label="Progres <?=e($g['name'])?>"><?=$p?>%</progress><div class="progress-caption"><span><?=$p?>% tercapai</span><span><?=rp($g['installment'])?> / <?=$g['frequency']==='Harian'?'hari':'minggu'?></span></div><p class="small muted"><?=$p>=100?'Target tercapai. Kerja bagus!':'Jadwal berikutnya: '.pretty_date(next_due($g))?></p><a class="btn secondary full" href="deposit.php?goal=<?=e($g['id'])?>">Tambah tabungan</a></article><?php endforeach; endif ?></section></div><?php page_end(); ?>
