<?php
require __DIR__.'/includes/app.php';
if (!empty($_SESSION['user'])) go('beranda.php');
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
 $username = trim((string)($_POST['username'] ?? ''));
 if (in_array($username, DEMO_USERNAMES, true) && hash_equals(DEMO_PASSWORD, (string)($_POST['password'] ?? ''))) {
  session_regenerate_id(true); $_SESSION['user'] = $username; $_SESSION['csrf'] = bin2hex(random_bytes(32)); go('beranda.php');
 }
 $error = 'Username atau password salah.';
}
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Login | Tabung Yuk</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/style.css"><script src="assets/app.js" defer></script></head><body class="login-body"><main class="login-layout"><section class="login-story"><a class="brand" href="login.php"><span class="brand-mark">ty.</span><span>Tabung Yuk<small>SEDIKIT JADI BUKIT</small></span></a><div class="story-content"><span class="story-label">MULAI KEBIASAAN BAIKMU</span><h1>Mimpi besar.<br>Mulai dari<br><em>tabungan kecil.</em></h1><p>Atur jadwal, sisihkan uang, dan lihat tujuanmu semakin dekat.</p><div class="story-progress"><div><span>LANGKAH MENUJU TUJUAN</span><b>01 / 03</b></div><div class="steps"><i></i><i></i><i></i></div><p>Rencanakan · Sisihkan · Wujudkan</p></div></div><small>Proyek lintas bidang · Keuangan & Informatika</small></section><section class="login-form-wrap"><div class="login-form"><span class="eyebrow">SELAMAT DATANG KEMBALI</span><h2>Masuk ke tabunganmu</h2><p>Langkah kecil hari ini, bekal untuk nanti.</p><?php if($error): ?><div class="alert error" role="alert"><?=e($error)?></div><?php endif ?><form method="post" action="login.php"><?=csrf()?><label for="username">Username</label><input id="username" name="username" autocomplete="username" placeholder="Masukkan username" required value="<?=old('username')?>"><label for="password">Password</label><div class="password-wrap"><input id="password" type="password" name="password" autocomplete="current-password" placeholder="Masukkan password" required><button type="button" id="toggle-password" aria-controls="password" aria-pressed="false">Lihat</button></div><button class="btn primary full" type="submit">Masuk</button></form><p class="small muted">Simulasi tanpa pembayaran nyata. Data disimpan sementara selama sesi dan dihapus saat keluar.</p></div><div class="login-credit">Kelompok 5 · Farisah, Benaya, Andrian, Almi, Lutfi</div></section></main></body></html>
