<?php
require __DIR__.'/includes/app.php'; require_login();
$id=(string)($_GET['id']??'');
if(!isset($_SESSION['transactions'][$id])) { notice('Transaksi tidak ditemukan. Pilih transaksi melalui riwayat.','error'); go('riwayat.php'); }
if($_SERVER['REQUEST_METHOD']==='POST') {
 $action=(string)($_POST['action']??''); $t=&$_SESSION['transactions'][$id];
 if($t['status']!=='pending') { notice('Transaksi sudah selesai atau kedaluwarsa; saldo tidak ditambahkan lagi.','info'); }
 elseif($action==='confirm') { $t['status']='success'; $t['paid_at']=time(); notice('Simulasi berhasil. '.rp($t['total']).' masuk ke tabungan.'); }
 elseif($action==='cancel') { $t['status']='cancelled'; notice('Deposit dibatalkan. Saldo tidak berubah.','info'); }
 else { notice('Tindakan tidak dikenali.','error'); }
 unset($t); go('pembayaran.php?id='.$id);
}
$t=$_SESSION['transactions'][$id];
page_start('Pembayaran','deposit','Periksa nominal dan selesaikan simulasi depositmu.');
?><a class="back-link" href="riwayat.php">Kembali ke riwayat</a><div class="two-col payment-grid"><section class="panel qr-panel"><span class="eyebrow">PEMBAYARAN QRIS</span><h2><?=e(goal_name($t['goal_id']))?></h2><?=badge($t['status'])?><div class="qr-area"><?php if(is_file(__DIR__.'/assets/qris.png')): ?><img src="assets/qris.png" alt="Gambar QRIS yang dipasang pemilik proyek"><?php else: ?><div class="qr-placeholder"><span class="qr-corner tl"></span><span class="qr-corner tr"></span><span class="qr-corner bl"></span><span class="qr-corner br"></span><strong>AREA GAMBAR QRIS</strong><span>Tempat untuk gambar<br>QRIS payment</span></div><?php endif ?></div><p class="small muted">Mode simulasi · Jangan transfer uang sungguhan.</p><div class="info-note">Gambar QRIS hanya ditampilkan. Aplikasi belum terhubung dengan layanan pembayaran.</div></section><section class="panel"><div class="section-title"><h2>Rincian deposit</h2><span class="icon-box soft"><?=icon('wallet')?></span></div><dl class="details"><dt>ID transaksi</dt><dd class="mono"><?=e(strtoupper($id))?></dd><dt>Dibuat</dt><dd><?=date('d/m/Y H:i',$t['created'])?> WIB</dd><dt>Nominal deposit</dt><dd><?=rp($t['amount'])?></dd><dt>Kode acak</dt><dd>+ <?=str_pad((string)$t['code'],3,'0',STR_PAD_LEFT)?></dd><dt>Keterangan</dt><dd><?=e($t['note']!==''?$t['note']:'-')?></dd></dl><div class="payment-total"><span>Total pembayaran</span><strong><?=rp($t['total'])?></strong><small>Termasuk tambahan kode acak</small></div><p class="small">Saldo yang masuk jika berhasil: <strong><?=rp($t['total'])?></strong>.</p><?php if($t['status']==='pending'): ?><div class="expiry">Berlaku hingga <?=date('d/m/Y H:i',$t['expires'])?> WIB <span data-expires="<?=$t['expires']?>"></span></div><form method="post" action="pembayaran.php?id=<?=e($id)?>"><?=csrf()?><button class="btn primary full" name="action" value="confirm" type="submit"><?=icon('check')?>Simulasikan pembayaran berhasil</button><button class="btn ghost full" name="action" value="cancel" type="submit">Batalkan deposit</button></form><?php else: ?><div class="alert <?=$t['status']==='success'?'success':'info'?>"><?=$t['status']==='success'?'Deposit sudah tercatat sekali pada saldo tabungan.':'Transaksi ditutup. Anda dapat membuat deposit baru.'?></div><a class="btn primary full" href="<?=$t['status']==='success'?'dashboard.php':'deposit.php'?>"><?=$t['status']==='success'?'Lihat dashboard':'Buat deposit baru'?></a><?php endif ?></section></div><?php page_end(); ?>
